travelly/locations/forms.py
from flask import flash
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError
from flask_login import current_user
from travelly.models import Location
from travelly.locations.utils import remove_accents, get_lat_lng


class AddLocationForm(FlaskForm):
    street = StringField(
        "Street", validators=[DataRequired()], render_kw={"placeholder": "Street"}
    )
    number = StringField(
        "Number", validators=[DataRequired()], render_kw={"placeholder": "Number"}
    )  # string, because numbers can be with letters ex. '48A'
    code = StringField(
        "Code", validators=[DataRequired()], render_kw={"placeholder": "City Code"}
    )
    city = StringField(
        "City", validators=[DataRequired()], render_kw={"placeholder": "City"}
    )

    submit = SubmitField("Add Location")


class UpdateLocationForm(FlaskForm):
    street = StringField(
        "Street", validators=[DataRequired()], render_kw={"placeholder": "Street"}
    )
    number = StringField(
        "Number", validators=[DataRequired()], render_kw={"placeholder": "Number"}
    )  # sting, because numbers can be with letters ex. '48A'
    code = StringField(
        "Code", validators=[DataRequired()], render_kw={"placeholder": "City Code"}
    )
    city = StringField(
        "City", validators=[DataRequired()], render_kw={"placeholder": "City"}
    )

    submit = SubmitField("Update")


# class MultiCheckboxField(SelectMultipleField):
#     widget = widgets.ListWidget(prefix_label=False)
#     option_widget = widgets.CheckboxInput()

# class DeleteForm(FlaskForm):
#     choices = MultiCheckboxField('Routes', coerce=int)
#     submit = SubmitField("Set User Choices")


class CSVForm(FlaskForm):
    csv = FileField("Upload CSV", validators=[FileAllowed(["csv"])])
    submit = SubmitField("Upload")

travelly/locations/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from travelly.travelly import db
from travelly.locations.forms import AddLocationForm, UpdateLocationForm, CSVForm
from travelly.models import Location
from travelly.locations.utils import (
    get_lat_lng,
    validate_location,
    remove_accents,
    import_csv,
    save_csv,
    add_location_to_planner,
    remove_location_from_planner
)

locations = Blueprint("locations", __name__)


@locations.route("/location", methods=["GET", "POST"])
@login_required
def location():
    page = request.args.get("page", 1, type=int)
    locations = (
        Location.query.filter(Location.user_id == current_user.id)
        .order_by(Location.id)
        .paginate(page=page, per_page=10)
    )

    add_location_form = AddLocationForm()
    if add_location_form.validate_on_submit():
        street = remove_accents(add_location_form.street.data).capitalize()
        number = remove_accents(add_location_form.number.data).upper()
        code = add_location_form.code.data
        city = remove_accents(add_location_form.city.data).capitalize()

        value = validate_location(
            street=street, number=number, code=code, city=city, user_id=current_user.id
        )
        if type(value) == str:
            flash(value, "danger")
            return redirect(url_for("locations.new_location"))
        else:
            lat = value[0]
            lng = value[1]

        location = Location(
            street=street,
            number=number,
            code=code,
            city=city,
            lat=lat,
            lng=lng,
            user_id=current_user.id,
        )
        db.session.add(location)
        db.session.commit()
        flash("Your location has been added!", "success")
        return redirect(url_for("locations.location"))

    CSV_form = CSVForm()
    if CSV_form.validate_on_submit():
        csv_file = save_csv(CSV_form.csv.data)
        import_csv(csv_file, user_id=current_user.id)

        return redirect(url_for("locations.location"))
    return render_template(
        "location/location.html",
        locations=locations,
        add_location_form=add_location_form,
        CSV_form=CSV_form,
    )


@locations.route("/location/new", methods=["GET", "POST"])
@login_required
def new_location():
    form = AddLocationForm()
    if form.validate_on_submit():
        street = remove_accents(form.street.data).capitalize()
        number = remove_accents(form.number.data).upper()
        code = form.code.data
        city = remove_accents(form.city.data).capitalize()

        value = validate_location(
            street=street, number=number, code=code, city=city, user_id=current_user.id
        )
        if type(value) == str:
            flash(value, "danger")
            return redirect(url_for("locations.new_location"))
        else:
            lat = value[0]
            lng = value[1]

        location = Location(
            street=street,
            number=number,
            code=code,
            city=city,
            lat=lat,
            lng=lng,
            user_id=current_user.id,
        )
        db.session.add(location)
        db.session.commit()
        flash("Your location has been added!", "success")
        return redirect(url_for("locations.location"))
    return redirect(url_for("locations.location"))


@locations.route("/location/<int:location_id>/delete", methods=["POST"])
@login_required
def delete_location(location_id):
    location = Location.query.get_or_404(location_id)
    if location.author != current_user:
        abort(403)
    try:
        db.session.delete(location)
        db.session.commit()
        flash("This location has been deleted!", "success")
        return redirect(url_for("locations.location"))
    except:
        flash("There was an error deleting that location")


@locations.route("/location/selected", methods=["GET", "POST"])
def selected():
    if request.method == "POST":
        if request.form.get("action") == "Delete Selected":
            to_delete = request.form.getlist("location_checkbox")
            for location_id in to_delete:
                delete_location(location_id)

        if request.form.get("action") == "Add to Plan":
            to_add = request.form.getlist("location_checkbox")
            for location_id in to_add:
                if location_id:
                    add_location_to_planner(location_id, current_user)
        
        if request.form.get("action") == "Remove From Plan":
            to_remove = request.form.getlist("location_checkbox")
            for location_id in to_remove:
                if location_id:
                    remove_location_from_planner(location_id, current_user)
    return redirect(url_for("locations.location"))


@locations.route("/location/<int:location_id>/update", methods=["GET", "POST"])
@login_required
def update_location(location_id):
    location = Location.query.get_or_404(location_id)
    if location.author != current_user:
        abort(403)
    form = UpdateLocationForm()
    if form.validate_on_submit():
        street = remove_accents(form.street.data).capitalize()
        number = remove_accents(form.number.data).upper()
        code = form.code.data
        city = remove_accents(form.city.data).capitalize()

        value = validate_location(
            street=street, number=number, code=code, city=city, user_id=current_user.id
        )
        if type(value) == str:
            flash(value, "danger")
            return redirect(
                url_for("locations.update_location", location_id=location_id)
            )
        else:
            lat = value[0]
            lng = value[1]

        location.street = street
        location.number = number
        location.code = code
        location.city = city
        location.lat = lat
        location.lng = lng
        db.session.commit()
        flash("Your location has been updated!", "success")
        return redirect(url_for("locations.location"))
    else:
        form.street.data = location.street
        form.number.data = location.number
        form.code.data = location.code
        form.city.data = location.city
    return render_template("location/update_location.html", form=form)

travelly/plan/routes.py
from flask import render_template, Blueprint, redirect, url_for, request, flash
from flask_login import current_user, login_required
from flask_sqlalchemy import sqlalchemy
from travelly.travelly import db
from travelly.models import Location
from travelly.plan.utils import create_map, get_matrix, route_map
from travelly.locations.utils import add_location_to_planner, remove_location_from_planner

# from travelly.plan.BranchAndBound import TSP_bnb
from ortools.constraint_solver import routing_enums_pb2
from travelly.plan.algorithms.ORTools_solver import ORsolve
from travelly.plan.algorithms.my_NN import solve_my_NN
from travelly.plan.algorithms.my_nearest_insertion import solve_nearest_insertion
from travelly.plan.algorithms.my_furthest_insertion import solve_furthest_insertion
from travelly.plan.algorithms.lib_2opt import solve_2opt

plan = Blueprint("plan", __name__)


@plan.route("/planner")
@login_required
def planner():
    locations = Location.query.filter(Location.user_id == current_user.id).order_by(
        Location.id
    )

    map = create_map(locations=locations.order_by(Location.id))

    page = request.args.get("page", 1, type=int)
    planned_locations = Location.query.filter(
        (Location.user_id == current_user.id), (Location.in_planner == True)
    ).paginate(page=page, per_page=10)
    return render_template("planner/plan.html", map=map, locations=planned_locations)


@plan.route("/planner/add/<int:location_id>")
@login_required
def add(location_id):
    add_location_to_planner(location_id, current_user)
    return redirect(url_for("locations.location"))


@plan.route("/planner/remove/<int:location_id>")
@login_required
def remove(location_id):
    remove_location_from_planner(location_id, current_user)
    return redirect(url_for("locations.location"))


@plan.route("/planner/get_route", methods=["POST"])
@login_required
def get_route():
    if request.method == "POST":
        algorithm = request.form.get("algorithm")

        if algorithm == None:
            flash("Please choose an algorithm before proceeding", "danger")
            return redirect(url_for("plan.planner"))

        locations = Location.query.filter(
            (Location.user_id == current_user.id), (Location.in_planner == True)
        ).order_by(Location.id)

        locations_list = []
        for location in locations:
            loc = (
                location.street,
                location.number,
                location.code,
                location.city,
                location.lat,
                location.lng,
            )
            locations_list.append(loc)

        matrix = get_matrix(locations_list)

        if algorithm == "christofides":
            solver_method = routing_enums_pb2.FirstSolutionStrategy.CHRISTOFIDES
            path, cost = ORsolve(matrix, solver_method)

        elif algorithm == "path_cheapest_arc":
            solver_method = routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
            path, cost = ORsolve(matrix, solver_method)

        elif algorithm == "nearest_neighbour":
            path, cost = solve_my_NN(matrix)

        elif algorithm == "nearest_insertion":
            path, cost = solve_nearest_insertion(matrix)

        elif algorithm == "furthest_insertion":
            path, cost = solve_furthest_insertion(matrix)

        elif algorithm == "two_opt":
            path, cost = solve_2opt(matrix)
        else:
            abort(404)

        ordered_locations = []
        for path_id in path:
            ordered_locations.append(locations_list[path_id])

        order = []
        for item in ordered_locations:
            order.append(item[0])
        print(order)
        page = request.args.get("page", 1, type=int)
        # locations = locations.order_by(sqlalchemy.func.field(Location.street, *order))

        # loc

        map = route_map(locations=ordered_locations)

        return render_template(
            "planner/planned_route.html",
            map=map,
            locations= ordered_locations
            # locations=locations.paginate(page=page, per_page=10),
        )

travelly/templates/location/location.html
{% extends "base.html" %}
{% block title %}
    Locations
{% endblock  title%}

{% block content %}
  <!-- Head -->
  <section class="location-head bg-primary py-3">
    <div class="container grid">
      <div>
        <h1 class="xl">Locations</h1>
        <p class="lead">Manage and add your locations here</p>
      </div>
      <img src="{{ url_for('static', filename='images/locations.svg')}}" alt="">
    </div>
  </section>

  <!-- Locations content -->
  <section class="location-content bg-light">
    <!-- If there are no locations -->  
    {% if locations.total < 1 %}
    <div class="container grid">
      <!-- Add Start Form -->
      <div class="add-start-form card">
        <form method="POST" action="">
          {{ add_location_form.hidden_tag() }}
          <fieldset class="">
              <legend class="">Add start</legend>
              <div class="">
                <!-- Street -->
                  {% if add_location_form.street.errors %}
                      {{ add_location_form.street(class="form-control is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in add_location_form.street.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ add_location_form.street(class="form-control") }}
                  {% endif %}
              </div>
              <!-- Number -->
              <div class="">
                  {% if add_location_form.number.errors %}
                      {{ add_location_form.number(class="form-control is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in add_location_form.number.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ add_location_form.number(class="form-control") }}
                  {% endif %}
              </div>
              <!-- City Code -->
              <div class="">
                  {% if add_location_form.code.errors %}
                      {{ add_location_form.code(class="form-control is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in add_location_form.code.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ add_location_form.code(class="form-control") }}
                  {% endif %}
              </div>
              <!-- City -->
              <div class="">
                  {% if add_location_form.city.errors %}
                      {{ add_location_form.city(class="form-control is-invalid") }}
                      <div class="invalid-feedback">
                          {% for error in add_location_form.city.errors %}
                              <span>{{ error }}</span>
                          {% endfor %}
                      </div>
                  {% else %}
                      {{ add_location_form.city(class="form-control") }}
                  {% endif %}
              </div>
          </fieldset>
          <!-- Submit -->
          <div class="form-group">
              {{ add_location_form.submit(class="btn") }}
          </div>
        </form>
      </div>

      <div class="no-locations-text">
        <h1>Add a starting point</h1>
        <p>There are no current locations in your database.
            First add a starting point from where you will start every trip.
        </p>
      </div>
    </div>

    <!-- If there are locations -->
    {% else %}
    <div class="container">
      <div class="locations-data grid-1">
        <form method="POST" class="selected-locations" action="{{ url_for('locations.selected') }}">
          <table class="location-table">
            <thead>
              <tr>
                <th><input type="checkbox" onclick="toggle(this)" id="check_all"></th>
                <!-- <th>Id</th> -->
                <th>Street</th>
                <th>Number</th>
                <th>City Code</th>
                <th>City</th>
                <th>Planner</th>
                <th>More</th>
              </tr>
            </thead>
            {% for location in locations.items %}
            <tbody>
              <tr>
                <td><input type="checkbox" value="{{ location.id}} " name="location_checkbox"></td>
                <!-- <td>{{ location.id }}</td> -->
                <td>{{ location.street }}</td>
                <td>{{ location.number }}</td>
                <td>{{ location.code }}</td>
                <td>{{ location.city }}</td>
                <td class="in-planner">
                  {% if location.in_planner == False %}
                    <a href="{{ url_for('plan.add', location_id=location.id) }}">Add</a>
                  {% else %}
                    <a href="{{ url_for('plan.remove', location_id=location.id) }}">Remove</a>
                  {% endif %}
                </td>
                <td class="action">
                  <a href="{{ url_for('locations.update_location', location_id=location.id) }}">Edit</a>
                </td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
          <div class="grid grid-3 text-center table-options">
            <input type="submit" name="action" class="delete-selected btn btn-outline-light" value="Delete Selected">
            <!-- Pagination -->
            <div class="location-pagination pagination">
              {% for page_num in locations.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                  {% if locations.page == page_num %}
                    <a class="pagination-main-page" href="{{ url_for('locations.location', locations=locations, page=page_num) }}">{{ page_num }}</a>
                  {% else %}
                    <a class="pagination-secondary-page" href="{{ url_for('locations.location', locations=locations, page=page_num) }}">{{ page_num }}</a>
                  {% endif %}
                {% else %}
                  ...
                {% endif %}
              {% endfor %}
            </div>
            <input type="submit" name="action" class="add-selected btn btn-outline-light" value="Add to Plan">
            <input type="submit" name="action" class="remove-selected btn btn-outline-light" value="Remove From Plan">
          </div>
        </form>
      </div>
    </div>
  </section>
    
  <!-- Add Locations -->
  <section class="add-locations my-2">
    <div class="container grid">
      <!-- Add Locations -->
      <div class="add-location-form card">
        <form method="POST" action="">
          {{ add_location_form.hidden_tag() }}
          <fieldset class="">
            <legend class="">Add Location</legend>
            <div class="">
              <!-- Street -->
                {% if add_location_form.street.errors %}
                    {{ add_location_form.street(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in add_location_form.street.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ add_location_form.street(class="form-control") }}
                {% endif %}
            </div>
            <!-- Number -->
            <div class="">
                {% if add_location_form.number.errors %}
                    {{ add_location_form.number(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in add_location_form.number.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ add_location_form.number(class="form-control") }}
                {% endif %}
            </div>
            <!-- City Code -->
            <div class="">
                {% if add_location_form.code.errors %}
                    {{ add_location_form.code(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in add_location_form.code.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ add_location_form.code(class="form-control") }}
                {% endif %}
            </div>
            <!-- City -->
            <div class="">
                {% if add_location_form.city.errors %}
                    {{ add_location_form.city(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in add_location_form.city.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ add_location_form.city(class="form-control") }}
                {% endif %}
            </div>
        </fieldset>
        <!-- Submit -->
        <div class="form-group">
            {{ add_location_form.submit(class="btn") }}
        </div>
      </form>
    </div>
    <!-- Add locations from CSV -->
    <div class="CSV-form card">
      <form method="POST"  action="" enctype="multipart/form-data">
        {{ CSV_form.hidden_tag() }}
          <fieldset class="CSV-form">
            <legend class="">Load CSV</legend>
            <p>
              Don't want to input all your data by hand?
              No worries! We've got the solution for you, upload 
              all your data in a CSV following the format:
            </p>
            <h3>Street, Number, Code, City</h3>
            <h2>Add locations in CSV</h2>
            <label class="file">
              {{ CSV_form.csv }}
            </label>
            {% if CSV_form.csv.errors %}
              {% for error in CSV_form.csv.errors %}
                <span class="text-danger">{{ error }}</span>
              {% endfor %}
            {% endif %}      
            <div class="">
              {{ CSV_form.submit(class="btn") }}
            </div>
          </fieldset>
      </form>
    </div>
  </section>
  {% endif %}
{% endblock content %}

travelly/templates/location/update_location.html
{% extends "base.html" %}
{% block title %}
    Update
{% endblock title %}

{% block content %}
<!-- update location -->
<section class="edit-location">
    <div class="container grid">
        <div class="edit-location-text">
            <h1>Edit location detail</h1>
            <p> Need to change your location detail? Fill the fields
                you want to change and update them!
            </p>
        </div>

        <div class="edit-location-form card">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="">
                    <legend class="">Update Location</legend>
                    <div class="">
                        {{ form.street.label }}
                        {% if form.street.errors %}
                            {{ form.street }}
                            <div class="invalid-feedback">
                                {% for error in form.street.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.street }}
                        {% endif %}
                    </div>
                    <div class="">
                        {{ form.number.label }}
                        {% if form.number.errors %}
                            {{ form.number }}
                            <div class="invalid-feedback">
                                {% for error in form.number.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.number }}
                        {% endif %}
                    </div>
                    <div class="">
                        {{ form.code.label }}
                        {% if form.code.errors %}
                            {{ form.code }}
                            <div class="invalid-feedback">
                                {% for error in form.code.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.code }}
                        {% endif %}
                    </div>
                    <div class="">
                        {{ form.city.label }}
                        {% if form.city.errors %}
                            {{ form.city|capitalize }}
                            <div class="invalid-feedback">
                                {% for error in form.city.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.city }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="edit-location-submit">
                    {{ form.submit(class="btn") }}
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}