travelly/main/routes.py
from flask import render_template, request, Blueprint

main = Blueprint("main", __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template("main/home.html")


@main.route("/about")
def about():
    return render_template("main/about.html")

travelly/users/routes.py
from flask import render_template, url_for, redirect, request, flash, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from travelly.travelly import db, bcrypt
from travelly.models import User, Location
from travelly.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
)
from travelly.users.utils import save_picture, send_reset_email


users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in", "success")
        return redirect(url_for("users.login"))
    return render_template("user/register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("locations.location"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return (
                redirect(next_page)
                if next_page
                else redirect(url_for("locations.location"))
            )
        else:
            flash("Login Unsuccessful. Please check email and password", "danger")
    return render_template("user/login.html", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            old_pic = current_user.image_file
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            if old_pic != "default.jpg":
                os.remove(os.path.join(users.root_path, "static/profile_pics", old_pic))
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template("user/account.html", image_file=image_file, form=form)


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first()
            send_reset_email(user)
        except:
            pass
        flash("An email has been sent with instructions to reset your password")
        return redirect(url_for("users.login"))
    return render_template("user/reset_request.html", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated! You are now able to log in", "success")
        return redirect(url_for("users.login"))
    return render_template("user/reset_token.html", form=form)

travelly/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/utilities.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css')}}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <!-- Navbar  -->
    <div class="navbar">
        <div class="container flex">
            <h1 class="logo">Travelly</h1>
            
            <nav>
                
                <ul>
                    <li><a href="{{ url_for('main.home') }}">Home</a></li>
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('plan.planner') }}">Plan</a></li>
                        <li><a href="{{ url_for('locations.location') }}">Locations</a></li>
                        <li><a href="{{ url_for('users.account') }}">Account</a></li>
                        <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                    {% else %}
                        <li><a href="{{ url_for('main.about') }}">About</a></li>
                        <li><a href="{{ url_for('users.login') }}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>
        
    </header>


    <main role="main">
        <!-- Flashing Messages -->
        <div class='flashed-message'>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>

        {% block content %}
        {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="footer bg-dark py-5">
        <div class="container grid grid-3">
            <div>
                <h1>Travelly</h1>
                <p>Copyright &copy; 2020</p>
            </div>
            <nav>
                <ul>
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('plan.planner') }}">Plan</a></li>
                        <li><a href="{{ url_for('locations.location') }}">Locations</a></li>
                        <li><a href="{{ url_for('users.account') }}">Account</a></li>
                        <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                    {% else %}
                        <li><a href="{{ url_for('main.home') }}">Home</a></li>
                        <li><a href="{{ url_for('main.about') }}">About</a></li>
                        <li><a href="{{ url_for('users.login') }}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
            <div class="social">
                <a href="#"><i class="fab fa-github fa-2x"></i></a>
                <a href="#"><i class="fab fa-facebook fa-2x"></i></a>
                <a href="#"><i class="fab fa-instagram fa-2x"></i></a>
                <a href="#"><i class="fab fa-twitter fa-2x"></i></a>
            </div>
        </div>
    </footer>

    <script type="text/javascript" src="{{ url_for('static', filename='script.js')}}"></script>
</body>
</html>