travelly/plan/routes.py
from flask import render_template, Blueprint, redirect, url_for, request, flash
from flask_login import current_user, login_required
from flask_sqlalchemy import sqlalchemy
from travelly.travelly import db
from travelly.models import Location
from travelly.plan.utils import create_map, get_matrix, route_map
from travelly.locations.utils import add_location_to_planner, remove_location_from_planner

# from travelly.plan.BranchAndBound import TSP_bnb
from ortools.constraint_solver import routing_enums_pb2
from travelly.plan.algorithms.ORTools_solver import ORsolve
from travelly.plan.algorithms.my_NN import solve_my_NN
from travelly.plan.algorithms.my_nearest_insertion import solve_nearest_insertion
from travelly.plan.algorithms.my_furthest_insertion import solve_furthest_insertion
from travelly.plan.algorithms.lib_2opt import solve_2opt

plan = Blueprint("plan", __name__)


@plan.route("/planner")
@login_required
def planner():
    locations = Location.query.filter(Location.user_id == current_user.id).order_by(
        Location.id
    )

    map = create_map(locations=locations.order_by(Location.id))

    page = request.args.get("page", 1, type=int)
    planned_locations = Location.query.filter(
        (Location.user_id == current_user.id), (Location.in_planner == True)
    ).paginate(page=page, per_page=10)
    return render_template("planner/plan.html", map=map, locations=planned_locations)


@plan.route("/planner/add/<int:location_id>")
@login_required
def add(location_id):
    add_location_to_planner(location_id, current_user)
    return redirect(url_for("locations.location"))


@plan.route("/planner/remove/<int:location_id>")
@login_required
def remove(location_id):
    remove_location_from_planner(location_id, current_user)
    return redirect(url_for("locations.location"))


@plan.route("/planner/get_route", methods=["POST"])
@login_required
def get_route():
    if request.method == "POST":
        algorithm = request.form.get("algorithm")

        if algorithm == None:
            flash("Please choose an algorithm before proceeding", "danger")
            return redirect(url_for("plan.planner"))

        locations = Location.query.filter(
            (Location.user_id == current_user.id), (Location.in_planner == True)
        ).order_by(Location.id)

        locations_list = []
        for location in locations:
            loc = (
                location.street,
                location.number,
                location.code,
                location.city,
                location.lat,
                location.lng,
            )
            locations_list.append(loc)

        matrix = get_matrix(locations_list)

        if algorithm == "christofides":
            solver_method = routing_enums_pb2.FirstSolutionStrategy.CHRISTOFIDES
            path, cost = ORsolve(matrix, solver_method)

        elif algorithm == "path_cheapest_arc":
            solver_method = routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC
            path, cost = ORsolve(matrix, solver_method)

        elif algorithm == "nearest_neighbour":
            path, cost = solve_my_NN(matrix)

        elif algorithm == "nearest_insertion":
            path, cost = solve_nearest_insertion(matrix)

        elif algorithm == "furthest_insertion":
            path, cost = solve_furthest_insertion(matrix)

        elif algorithm == "two_opt":
            path, cost = solve_2opt(matrix)
        else:
            abort(404)

        ordered_locations = []
        for path_id in path:
            ordered_locations.append(locations_list[path_id])

        order = []
        for item in ordered_locations:
            order.append(item[0])
        print(order)
        page = request.args.get("page", 1, type=int)
        # locations = locations.order_by(sqlalchemy.func.field(Location.street, *order))

        # loc

        map = route_map(locations=ordered_locations)

        return render_template(
            "planner/planned_route.html",
            map=map,
            locations= ordered_locations
            # locations=locations.paginate(page=page, per_page=10),
        )

travelly/templates/planner/plan.html
{% extends "base.html" %}
{% block title %}
    Plan
{% endblock title %}

{% block content %}
  <!-- Head -->
  <section class="planner-head bg-primary py-3">
    <div class="container grid">
      <div>
        <h1 class="xl">Planner</h1>
        <p class="lead">Plan your route and start your trip</p>
      </div>
      <img src="{{ url_for('static', filename='images/notes.svg')}}" alt="">
    </div>
  </section>

  <!-- Plan description with Map -->
  <section class="map-content bg-light py-2">
    <div class="container grid">
      <div class="map-content-text">
        <h1>Plan your route</h1>
        <p> With your locations selected for planning, all that
          is left to do is planning your trip! Choose an algorithm, 
          click the button and wait for the magic to happen.
        </p>
        
        {% if locations.total < 1 %}
          <h2>There are no locations to travel to.</h2>
          <h3 class="btn"><a href="{{url_for('locations.location')}}" class="text-light">Add them here!</a></h3>
        
        {% else %}
          <div class="select-box">
            <form method="POST" class="get_route" action="{{ url_for('plan.get_route') }}">
              <div class="options-container">  
                <div class="option">
                  <input type="radio" value="christofides" class="radio" id="christofides" name="algorithm"/>
                  <label for="christofides">Christofides</label>
                </div>
                <div class="option">
                  <input type="radio" class="radio" id="path_cheapest_arc" name="algorithm" value="path_cheapest_arc"/>
                  <label for="path_cheapest_arc">Path Cheapest Arc</label>
                </div>
                <div class="option">
                  <input type="radio" class="radio" id="nearest_neighbour" name="algorithm" value="nearest_neighbour"/>
                  <label for="nearest_neighbour">Nearest Neighbour</label>
                </div>
                <div class="option">
                  <input type="radio" class="radio" id="nearest_insertion" name="algorithm" value="nearest_insertion"/>
                  <label for="nearest_insertion">Nearest Insertion</label>
                </div>
                <div class="option">
                  <input type="radio" class="radio" id="furthest_insertion" name="algorithm" value="furthest_insertion"/>
                  <label for="furthest_insertion">Furtherst Insertion</label>
                </div>
                <div class="option">
                  <input type="radio" class="radio" id="two_opt" name="algorithm" value="two_opt"/>
                  <label for="two_opt">2-opt</label>
                </div>
              </div>
              <input type="submit" class="btn" name="submit_button" value="Show Route">
              <div class="selected">
                Choose your algorithm
              </div>
            </form>
          </div>
        {% endif %}
      </div>

      <div class="map card">
        {{ map|safe }}
      </div>
    </div>
  </section>

  <!-- Locations Planned -->
  <section class="locations-planned">
    <div class="container">
      <div class="locations-plan-data grid-1">
        {% if locations.total < 1 %}
        {% else %}
          <h1>Selected locations to travel to:</h1>
          <table class="location-table">
            <thead>
              <tr>
                <th>Street</th>
                <th>Number</th>
                <th>City Code</th>
                <th>City</th>
              </tr>
            </thead>

            {% for location in locations.items %}
              <tbody>
                <tr>
                  <td>{{ location.street }}</td>
                  <td>{{ location.number }}</td>
                  <td>{{ location.code }}</td>
                  <td>{{ location.city }}</td>
                </tr>
              </tbody>
            {% endfor %}
          </table>
          <!-- Pagination -->
          <div class="plan-pagination-box">
            <div class="location-planned-pagination pagination">
              {% for page_num in locations.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=3) %}
                {% if page_num %}
                  {% if locations.page == page_num %}
                    <a class="pagination-main-page" href="{{ url_for('locations.location', locations=locations, page=page_num) }}">{{ page_num }}</a>
                  {% else %}
                    <a class="pagination-secondary-page" href="{{ url_for('locations.location', locations=locations, page=page_num) }}">{{ page_num }}</a>
                  {% endif %}
                {% else %}
                  ...
                {% endif %}
              {% endfor %}
            </div>
          </div>
        {% endif %}
      </div>
    </div>
  </section>



 
{% endblock content %}

travelly/templates/planner/planned_route.html
{% extends "base.html" %}
{% block title %}
    Your Route
{% endblock title %}

{% block content %}
  <!-- Head -->
  <section class="planned-route-head bg-primary py-3">
    <div class="container grid">
      <div>
        <h1 class="xl">Your route</h1>
        <p class="lead">Here you can find the shortest route
                        designed for your needs.
        </p>
      </div>
      <img src="{{ url_for('static', filename='images/selection.svg')}}" alt="">
    </div>
  </section>

  <!-- Planned trip description with Map -->
  <section class="map-content-planned bg-light py-2">
    <div class="container grid">
      <div class="map-content-planned-text">
        <h1>The shortest route</h1>
        <p>Here is the shortest route found by the algorithm you chose.
          Follow the locations bellow in order, so you can have 
          the shortest trip.</canvas>
        </p>
      </div>

      <div class="map card">
        {{ map|safe }}
      </div>
    </div>
  </section>

  <!-- Ordered locations table -->
  <section class="locations-ordered">
    <div class="container">
      <div class="locations-ordered-data grid-1">
        <h1>Follow these locations in order:</h4>
        <table class="location-table">
          <thead>
            <tr>
              <th>Street</th>
              <th>Number</th>
              <th>City Code</th>
              <th>City</th>
            </tr>
          </thead>

          {% for location in locations %}
            <tbody>
              <tr>
                <td>{{ location[0] }}</td>
                <td>{{ location[1] }}</td>
                <td>{{ location[2] }}</td>
                <td>{{ location[3] }}</td>
              </tr>
            </tbody>
          {% endfor %}
        </table>
        <!-- Pagination -->

      </div>
    </div>
  </section>

 
{% endblock content %}