travelly/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from travelly.models import User


class RegistrationForm(FlaskForm):
    username = StringField(
        "Username",
        validators=[DataRequired(), Length(min=2, max=20)],
        render_kw={"placeholder": "Username"},
    )
    email = StringField(
        "Email",
        validators=[DataRequired(), Email()],
        render_kw={"placeholder": "Email"},
    )
    password = PasswordField(
        "Password",
        validators=[DataRequired(), Length(min=6)],
        render_kw={"placeholder": "Password"},
    )
    confirm_password = PasswordField(
        "Confirm Password",
        validators=[DataRequired(), EqualTo("password")],
        render_kw={"placeholder": "Confirm Password"},
    )

    submit = SubmitField("Sign up")

    # def validate_field(self, field):
    #     if True:
    #         raise ValidationError('Validation Message')
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError(
                "That username is taken. Please choose a different one."
            )
            # flash('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError(
                "That email is already used. Please choose a different one."
            )
            # flash('That email is taken. Please choose a different one.')


class LoginForm(FlaskForm):
    email = StringField(
        "Email",
        validators=[DataRequired(), Email()],
        render_kw={"placeholder": "Email"},
    )
    password = PasswordField(
        "Password", validators=[DataRequired()], render_kw={"placeholder": "Password"}
    )
    remember = BooleanField("Remember Me")

    submit = SubmitField("Login")


class UpdateAccountForm(FlaskForm):
    username = StringField(
        "Username",
        validators=[DataRequired(), Length(min=2, max=20)],
        render_kw={"placeholder": "Username"},
    )
    email = StringField(
        "Email",
        validators=[DataRequired(), Email()],
        render_kw={"placeholder": "Email"},
    )
    picture = FileField(
        "Update Profile Picture",
        validators=[FileAllowed(["jpg", "png"])],
        render_kw={"placeholder": "Add Picture"},
    )
    submit = SubmitField("Update")

    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError(
                    "That username is taken. Please choose a different one."
                )
                flash("That username is taken. Please choose a different one.")

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError(
                    "That email is already used. Please choose a different one."
                )
                flash("That email is taken. Please choose a different one.")


class RequestResetForm(FlaskForm):
    email = StringField(
        "Email",
        validators=[DataRequired(), Email()],
        render_kw={"placeholder": "Email"},
    )
    submit = SubmitField("Send Email")

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            # we do nothing in order not to have some security issues. We don't want anyone to know
            # if a certain user exists or not
            pass


class ResetPasswordForm(FlaskForm):
    password = PasswordField(
        "Password", validators=[DataRequired()], render_kw={"placeholder": "Password"}
    )
    confirm_password = PasswordField(
        "Confirm Password",
        validators=[DataRequired(), EqualTo("password")],
        render_kw={"placeholder": "Confirm Password"},
    )
    submit = SubmitField("Reset Password")

travelly/users/routes.py
from flask import render_template, url_for, redirect, request, flash, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from travelly.travelly import db, bcrypt
from travelly.models import User, Location
from travelly.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
)
from travelly.users.utils import save_picture, send_reset_email


users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash("Your account has been created! You are now able to log in", "success")
        return redirect(url_for("users.login"))
    return render_template("user/register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("locations.location"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            return (
                redirect(next_page)
                if next_page
                else redirect(url_for("locations.location"))
            )
        else:
            flash("Login Unsuccessful. Please check email and password", "danger")
    return render_template("user/login.html", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            old_pic = current_user.image_file
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
            if old_pic != "default.jpg":
                os.remove(os.path.join(users.root_path, "static/profile_pics", old_pic))
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated!", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template("user/account.html", image_file=image_file, form=form)


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        try:
            user = User.query.filter_by(email=form.email.data).first()
            send_reset_email(user)
        except:
            pass
        flash("An email has been sent with instructions to reset your password")
        return redirect(url_for("users.login"))
    return render_template("user/reset_request.html", form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash("Your password has been updated! You are now able to log in", "success")
        return redirect(url_for("users.login"))
    return render_template("user/reset_token.html", form=form)

travelly/templates/user/account.html
{% extends "base.html" %}
{% block title %}Account{% endblock title %}

{% block content %}
  <!-- Head -->
  <section class="account-head bg-primary py-3">
    <div class="container grid">
      <div>
        <h1 class="xl">Account</h1>
        <p class="lead">Manage your account detail here</p>
      </div>
      <img src="{{ url_for('static', filename='images/profile.svg')}}" alt="">
    </div>
  </section>

<!-- Edit account -->
<section class="account">
    <div class="container grid">
        <div class="account-text">
            <h1>Update your account</h1>
            <p> Your account info is outdated? Fill in the
                form and update in now!
            </p>
        </div>

        <div class="update-account-form card">
            <img class="" src="{{ image_file }}">

            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="">
                    <div class="">
                        {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.username(class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="">
                        {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="update-photo">
                        {{ form.picture.label() }}
                        <label class="file">
                            {{ form.picture(class="") }}
                        </label>
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }} </span><br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="">
                    {{ form.submit(class="btn btn-outline-info") }}
            </form>
        </div>

    </div>
</section>
{% endblock content %}

travelly/templates/user/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock title %}

{% block content %}
<section class="login">
    <div class="container grid">
        <div class="login-text">
            <h1>Log In to your Account</h1>
            <p> Already have an account? Log in and start using all the tools
                you need!
            </p>
        </div>

        <div class="login-form card">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="">
                    <legend class="">Log In</legend>
                        <!-- Email -->
                        {% if form.email.errors %}
                            {{ form.email(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control") }}
                        {% endif %}
                        <!-- Password -->
                        {% if form.password.errors %}
                            {{ form.password(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control") }}
                        {% endif %}
                        <!-- Remember -->
                        {{ form.remember}}
                        {{ form.remember.label}}
                </fieldset>
    
                <div class="my-1">
                    {{ form.submit(class="btn") }}
                </div>
                <small class="">
                    Need An Account? <a class="" href="{{ url_for('users.register') }}">Sign Up Now</a>
                </small>
                <br>
                <small class="text-muted">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </form>
    
            <div class="">
                
            </div>
        </div>
    </div>
</section>
{% endblock content %}

travelly/templates/user/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock title %}

{% block content %}

<!-- Registration -->
<section class="register">
    <div class="container grid">
        <div class="register-text">
            <h1>Register an Account</h1>
            <p> Don't have an account yet? Fill out the form and 
                start your journey today!
            </p>
        </div>

        <div class="register-form card">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="">
                    <legend class="">Join Today</legend>
                        <!-- Username -->
                        {% if form.username.errors %}
                            {{ form.username(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control") }}
                        {% endif %}
                        <!-- Email -->
                        {% if form.email.errors %}
                            {{ form.email(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control") }}
                        {% endif %}
                        <!-- Password -->
                        {% if form.password.errors %}
                            {{ form.password(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control") }}
                        {% endif %}
                        <!-- Confirm Password -->
                        {% if form.confirm_password.errors %}
                            {{ form.confirm_password(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.confirm_password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.confirm_password(class="form-control form-control-lg") }}
                        {% endif %}
                </fieldset>
                <div class="my-1">
                    {{ form.submit(class="btn") }}
                </div>
                <small class="">
                    Already Have An Account? <a class="" href="{{ url_for('users.login') }}">Sign In</a>
                </small>
            </form>

        </div>  
    </div> 
</section>

{% endblock content %}

travelly/templates/user/reset_request.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock title %}

{% block content %}
<section class="forgot-password">
    <div class="container grid">
        <div class="forgot-password-text">
            <h1>Forgot your password?</h1>
            <p> Don't worry, we've got your back! Fill in the form
                and we'll send you an email to change your password.
            </p>
        </div>

        <div class="forgot-password-form card">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="">
                    <legend class="">Reset Your Password</legend>
                    <!-- Email -->
                        {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="form-control") }}
                        {% endif %}
                </fieldset>
            
                <div class="">
                    {{ form.submit(class="btn") }}
                </div>
                
                <small class="">
                    Already Have An Account? <a class="" href="{{ url_for('users.login') }}">Sign In</a>
                </small>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

travelly/templates/user/reset_token.html
{% extends "base.html" %}
{% block title %}Reset Password{% endblock title %}

{% block content %}
<section class="reset-password">
    <div class="container grid">
        <div class="reset-password-text">
            <h1>Change Password</h1>
            <p> Fill out the form to change your password.
            </p>
        </div>

        <div class="reset-password-form card">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="">
                    <legend class="">Reset Password</legend>
                    <!-- Password -->
                        {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.password(class="form-control") }}
                        {% endif %}
                    <!-- Confirm Password -->
                        {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.confirm_password(class="form-control") }}
                        {% endif %}
                </fieldset>
            
                <div class="">
                    {{ form.submit(class="btn") }}
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}